USE MASTER
GO

IF DB_ID('QL_HSUT') IS NOT NULL --KTR CSDL TỒN TẠI CHƯA
	DROP DATABASE QL_HSUT --XÓA CSDL
	GO
CREATE DATABASE QL_HSUT --TẠO CSDL
GO

USE QL_HSUT
GO

CREATE TABLE DOANH_NGHIEP(
	TENCONGTY VARCHAR(50),
	MASOTHUE VARCHAR(10) NOT NULL,
	NGUOIDAIDIEN VARCHAR(30),
	EMAIL VARCHAR(30),
	DIACHI VARCHAR(50),
	MAUD VARCHAR(5),
	CONSTRAINT pk_DOANH_NGHIEP PRIMARY KEY(MASOTHUE),
)
GO

CREATE TABLE UNG_VIEN(
	ANH VARCHAR(12),
	CCCD VARCHAR(12) NOT NULL,
	HOTEN VARCHAR(30),
	SDT VARCHAR(10),
	DIACHI VARCHAR(50),
	CONSTRAINT pk_UNG_VIEN PRIMARY KEY(CCCD),
)
GO

CREATE TABLE BANG_CAP(
	MAHS VARCHAR(5),
	TENBANGCAP VARCHAR(20),
	LOAIBANGCAP VARCHAR(10),
	CHITIETBANGCAP VARCHAR(30),
	CONSTRAINT pk_BANG_CAP PRIMARY KEY(MAHS),
)
GO

CREATE TABLE UU_DAI(
	MAUD VARCHAR(5) NOT NULL,
	CHITIETUD VARCHAR(30),
	CONSTRAINT pk_UU_DAI PRIMARY KEY(MAUD),
)
GO

CREATE TABLE THANH_TOAN(
	LANTRA VARCHAR(1) NOT NULL,
	SOTIEN MONEY,
	NGAYTHANHTOAN DATE,
	PHUONGTHUCTT VARCHAR(10),
	MAQC VARCHAR(5) NOT NULL,
	CONSTRAINT pk_THANH_TOAN PRIMARY KEY(LANTRA),
)
GO

CREATE TABLE TT_QUANG_CAO(
	MAQC VARCHAR(5) NOT NULL,
	TONGSOTIEN MONEY,
	HOANTATTHANHTOAN VARCHAR(10),
	MATT VARCHAR(5) NOT NULL,
	CONSTRAINT pk_TT_QUANG_CAO PRIMARY KEY(MAQC),
)
GO

CREATE TABLE HINH_THUC(
	MAHINHTHUC VARCHAR(5) NOT NULL,
	TENHINHTHUC VARCHAR(20),
	CHITIETHINHTHUC VARCHAR(30),
	MATT VARCHAR(5) NOT NULL,
	CONSTRAINT pk_HINH_THUC PRIMARY KEY(MAHINHTHUC),
)
GO

CREATE TABLE TT_DANG_TUYEN(
	MATT VARCHAR(5) NOT NULL,
	VITRIDANGTUYEN VARCHAR(10),
	SOLUONGTUYENDUNG INT,
	BATDAUTUYENDUNG DATE,
	KETTHUCTUYENDUNG DATE,
	HANTUYENDUNG DATE,
	YEUCAU VARCHAR(20),
	MASOTHUE VARCHAR(10),
	CONSTRAINT pk_TT_DANG_TUYEN PRIMARY KEY(MATT),
)
GO

CREATE TABLE HO_SO_DA_XU_LY(
	MASOTHUE VARCHAR(10),
	MAHS VARCHAR(5),
	NGAYGUI DATE,
	PHANHOI VARCHAR(10),
	CONSTRAINT pk_HO_SO_DA_XU_LY PRIMARY KEY(MASOTHUE,MAHS),
)
GO

CREATE TABLE DANG_KY_UNG_TUYEN(
	MAHS VARCHAR(5) NOT NULL,
	NGAYNOPHOSO DATE,
	DUDIEUKIEN BIT,
	CCCD VARCHAR(12),
	MATT VARCHAR(5),
	CONSTRAINT pk_DANG_KY_UNG_TUUYEN PRIMARY KEY(MAHS),
)
GO


-- KHOÁ NGOẠI
ALTER TABLE HO_SO_DA_XU_LY
	ADD CONSTRAINT fk_HO_SO_DA_XU_LY__DOANH_NGHIEP
	FOREIGN KEY(MASOTHUE) REFERENCES DOANH_NGHIEP
	
GO

ALTER TABLE HO_SO_DA_XU_LY
	ADD CONSTRAINT fk_HO_SO_DA_XU_LY__DANG_KY_UNG_TUYEN
	FOREIGN KEY(MAHS) REFERENCES DANG_KY_UNG_TUYEN
GO

ALTER TABLE DANG_KY_UNG_TUYEN
	ADD CONSTRAINT fk_DANG_KY_UNG_TUYEN__UNG_VIEN
	FOREIGN KEY(CCCD) REFERENCES UNG_VIEN
GO

ALTER TABLE BANG_CAP
	ADD CONSTRAINT fk_BANG_CAP__DANG_KY_UNG_TUYEN 
	FOREIGN KEY(MAHS) REFERENCES DANG_KY_UNG_TUYEN

GO

ALTER TABLE TT_DANG_TUYEN
	ADD CONSTRAINT fk_TT_DANG_TUYEN__DANG_KY_UNG_TUYEN
	FOREIGN KEY(MATT) REFERENCES DANG_KY_UNG_TUYEN
GO

ALTER TABLE TT_DANG_TUYEN
	ADD CONSTRAINT fk_TT_DANG_TUYEN__DOANH_NGHIEP
	FOREIGN KEY(MASOTHUE) REFERENCES DOANH_NGHIEP
GO

ALTER TABLE HINH_THUC
	ADD CONSTRAINT fk_HINH_THUC__TT_DANG_TUYEN
	FOREIGN KEY(MATT) REFERENCES TT_DANG_TUYEN
GO

ALTER TABLE TT_QUANG_CAO
	ADD CONSTRAINT fk_TT_QUANG_CAO__TT_DANG_TUYEN
	FOREIGN KEY(MATT) REFERENCES TT_DANG_TUYEN
GO

ALTER TABLE THANH_TOAN
	ADD CONSTRAINT fk_THANH_TOAN__TT_QUANG_CAO
	FOREIGN KEY(MAQC) REFERENCES TT_QUANG_CAO
GO

ALTER TABLE DOANH_NGHIEP
	ADD CONSTRAINT fk_DOANH_NGHIEP__UU_DAI
	FOREIGN KEY(MAUD) REFERENCES UU_DAI
GO

